# Generated by Django 4.0.1 on 2022-01-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listnr', '0002_review_mix_error_review_recording_error_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rev_title',
            new_name='review_title',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='writing_advice',
            new_name='writing_changes',
        ),
    ]
